// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBk4Tz6kWfgONBAHeYLQWlWfXqugLzvWY',
    appId: '1:317958059758:web:c5a1278921f05b92bca5ff',
    messagingSenderId: '317958059758',
    projectId: 'wasl-cdcb6',
    authDomain: 'wasl-cdcb6.firebaseapp.com',
    storageBucket: 'wasl-cdcb6.firebasestorage.app',
    measurementId: 'G-1GLZ07ETRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaiHxvaYSYQ_GwIev6WbaUQlry-wW__g8',
    appId: '1:317958059758:android:f549d00bb159a957bca5ff',
    messagingSenderId: '317958059758',
    projectId: 'wasl-cdcb6',
    storageBucket: 'wasl-cdcb6.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn_UpQ32Sm2u6RDRnZ_hBionzm_ZoJLeQ',
    appId: '1:317958059758:ios:5ab8bbc2e3ea06cdbca5ff',
    messagingSenderId: '317958059758',
    projectId: 'wasl-cdcb6',
    storageBucket: 'wasl-cdcb6.firebasestorage.app',
    iosBundleId: 'com.ahmedalattas.wasl',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn_UpQ32Sm2u6RDRnZ_hBionzm_ZoJLeQ',
    appId: '1:317958059758:ios:5ab8bbc2e3ea06cdbca5ff',
    messagingSenderId: '317958059758',
    projectId: 'wasl-cdcb6',
    storageBucket: 'wasl-cdcb6.firebasestorage.app',
    iosBundleId: 'com.ahmedalattas.wasl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBk4Tz6kWfgONBAHeYLQWlWfXqugLzvWY',
    appId: '1:317958059758:web:5bba2540825f8bf6bca5ff',
    messagingSenderId: '317958059758',
    projectId: 'wasl-cdcb6',
    authDomain: 'wasl-cdcb6.firebaseapp.com',
    storageBucket: 'wasl-cdcb6.firebasestorage.app',
    measurementId: 'G-521ZMLJ7FZ',
  );
}
